version: "3.7"

services:
  pb-analytics:
    build: ./pocketbase/.
    container_name: pb-analytics
    restart: unless-stopped
    ports:
      - "8044:8044"
    volumes:
      - /data:/pb_data
  front-analytics:
    build: .
    container_name: front-analytics
    restart: unless-stopped
    ports:
      - "80:8045"